package dec.team3.spiritanimal.model;

public enum Kategorie {
    HUNDE, KATZEN, PFERDE, QUALLEN, VÖGEL, EXOTEN, WEITERE_NAGER, FISCHE, NAGER, KATZENARTIGE_TIERE, HAUSELFEN, DAMMWILD, SCHNABELTIERE, PINGUINE, SCHILDKRÖTEN
}
