version: "3.8"

services:
  
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    hostname: mongo
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - data:/data
    networks:
      - spiritnet
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - spiritnet
  
  backend:
    image: backend
    build:
      context: backend
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - spiritnet

#  frontend:
#    build: ./frontend/spiritanimal-frontend
#    image: frontend_vue
#    container_name: frontend
#    ports:
#      - 3000:8080
##    depends_on:
##      - backend
#    networks:
#      - spiritnet

#  nginx:
#    image: jwilder/nginx-proxy:latest
#    container_name: nginx
#    restart: always
#    environment:
#      DEFAULT_HOST: default.vhost
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./certs:/etc/nginx/certs
#      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  data: {}

networks:
  spiritnet:
    driver: bridge