version: "3.8"

services:
   
  frontend:
    build: ./frontend/spiritanimal-frontend
    image: frontend_vue
    container_name: frontend
    ports:
      - 3000:8080
    #    depends_on:
    #      - backend
    networks:
      - spiritnet
  
  backend:
    image: backend
    build:
      context: backend
    container_name: backend
    ports:
      - 8080:8080
    networks:
      - spiritnet
  
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    hostname: mongo
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - data:/data
    networks:
      - spiritnet
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - spiritnet

volumes:
  data: {}

networks:
  spiritnet:
    driver: bridge