version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    hostname: mongo
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - data:/data
    networks:
      - backdb
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - backdb

  front:
    build: ./frontend/spiritanimal-frontend
    image: de_frontend_vue
    container_name: frontend
    ports:
      - 3000:8080
#    depends_on:
#      - backend
    networks:
      - frontback

  backend:
    image: backend
    build:
      context: backend
    container_name: backend
    ports:
      - 8080:8080
    networks:
      - frontback
      - backdb

volumes:
  data: {}

networks:
  backdb:
    driver: bridge
  frontback:
    driver: bridge